[versions]
junit = "5.10.0"
jetbrainsAnnotations = "24.0.1"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrainsAnnotations" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
